# permissions for end users to edit registrars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: registrar-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
  name: registrar-editor-role
rules:
- apiGroups:
  - malygos.00n.fr
  resources:
  - registrars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - malygos.00n.fr
  resources:
  - registrars/status
  verbs:
  - get
