---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - malygos.00n.fr
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - malygos.00n.fr
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - malygos.00n.fr
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - malygos.00n.fr
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - malygos.00n.fr
  resources:
  - components/finalizers
  verbs:
  - update
- apiGroups:
  - malygos.00n.fr
  resources:
  - components/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - malygos.00n.fr
  resources:
  - registrars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - malygos.00n.fr
  resources:
  - registrars/finalizers
  verbs:
  - update
- apiGroups:
  - malygos.00n.fr
  resources:
  - registrars/status
  verbs:
  - get
  - patch
  - update
