apiVersion: malygos.00n.fr/v1
kind: Component
metadata:
  labels:
    app.kubernetes.io/name: component
    app.kubernetes.io/instance: component-sample
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controller
  name: component-sample
spec:
  # TODO(user): Add fields here
