# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/malygos.00n.fr_clusters.yaml
- bases/malygos.00n.fr_registrars.yaml
- bases/malygos.00n.fr_components.yaml
- bases/malygos.00n.fr_componentversions.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_clusters.yaml
#- path: patches/webhook_in_registrars.yaml
#- path: patches/webhook_in_components.yaml
#- path: patches/webhook_in_componentversions.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_clusters.yaml
#- path: patches/cainjection_in_registrars.yaml
#- path: patches/cainjection_in_components.yaml
#- path: patches/cainjection_in_componentversions.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

#configurations:
#- kustomizeconfig.yaml
